#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
    apt-mark manual fluxbox \
		mx-fluxbox-data \
        mx-idesktool \
        wmalauncher \
        gkrellm \
        mx-dockmaker \
        mxfb-docs \
        rofi \
        rofi-calc \
        mx-rofi-manager \
        grsync \
        exit-options \
        idesk \
        nitrogen \
        volumeicon-alsa \
        policykit-1-gnome \
        tint2 || :
fi


#DEBHELPER#
